backend:
  name: github
  repo: Joeeeeca/highfield-road-christmas-lights
  branch: gh-pages
  base_url: https://decap-cms-oauth.vercel.app

media_folder: "dist/images/uploads"  # where images are stored in your built site
public_folder: "/images/uploads"     # how those images are referenced in the site

collections:
  - name: "content"
    label: "Site Content"
    files:
      - label: "About Section"
        name: "about"
        file: "src/content/about.json"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Text", name: "text", widget: "text" }
          - { label: "Image", name: "image", widget: "image" }
